driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      image: corux/centos7-salt
      privileged: True
      run_command: /usr/sbin/init

provisioner:
  name: salt_solo
  formula: plex
  pillars-from-files:
    plex.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - plex
  state_top:
    base:
      "*":
        - plex

suites:
  - name: default
